### ISSUE TITLE
expressions

### ISSUE THREAD

**Issue by bigbigant** [Comos/tage#12]
$foo
$foo.bar
$foo.bar()
字符串：'string', "string"

布尔值：true, false

空: null

数字

逻辑运算符：&&,||,!

数学运算符：+,-,_,/,_*(幂乘),//(整除)

字符串连接运算符: ~

range运算符: .. (如1..9 或 'a'..'z')

in 操作符: 如 $item in $items

数组:此处所说的数组是php中得通用array概念。(既是map也是数组)。如 [$a,$b,$c] 、 [3:$a,'mykey':$b,]

**Comment by 13leaf** [comment]
[common parser algorithm](http://www.engr.mun.ca/~theo/Misc/exp_parsing.htm#grammar)
