### ISSUE TITLE
Milestone1的讨论

### ISSUE THREAD

**Issue by 13leaf** [Comos/tage#2]
1. Etag中对+操作符的编译结果是否考虑覆盖php默认+的实现?
   例如`{{a+b}}`转换到`etag_add(a,b)`而不是`((a)+(b))`。好处是可以直接实现ab为字符串时的连接行为，无需增加新的字符串concat符。(在其它模板引擎中使用~来做字符串连接)。覆盖的问题会增加函数开销，导致解释结果的性能下降。
2. Etag转换过程中使用的一些内置函数(原属api)Runtime怎么安置？
   例如1中的etag_add，是否直接在Runtime实现并作为一个全局函数?

下面是参考其它模板引擎的一些比较有趣的feature，看看是否有必要在后续考虑引入:
### 以[jade](http://jade-lang.com/)为代表的依靠缩写表达式来节约html的冗余性。以[slim](http://www.rubydoc.info/gems/slim/frames)举例:

``` slim
body
  p
    |
      This is a test of the text block.
```

  结果将是

``` html
<body><p>This is a test of the text block.</p></body>
```
### list作用域

类似[Handlebars](http://handlebarsjs.com/)可以这样使用.
`{{#list people}}{{firstName}} {{lastName}}{{/list}}`
等同于`{{people.firstName}} {{people.lastName}}`
### View的数据绑定与共享传递

在[laravel](http://laravel.com/docs/5.0/views)中可以对View绑定数据提供者，以此实现MVC。还可以让视图之间做数据传递(可以解决之前专题组件的联动更新问题?)。

**Comment by bigbigant** [comment]
必要的函数应该是在Runtime下实现，但应该是带着namespace的, 类似 Etag\Runtime\op_add。
也可以实现为Etag\Runtime\Op::add()

用+替代~, 从兼容旧版的角度来看，不建议进行。

list作用域 这个觉得不错。

缩写表达式来简化 HTML标签 和 View数据绑定还没看，了解中：）

**Comment by bigbigant** [comment]
支持宏不错
多终端 适配
I18n也不错

**Comment by 13leaf** [comment]
支持宏是什么呀?
多终端适配和i18n的具体方案是?

**Comment by bigbigant** [comment]
Macro looks like follows.

```
{#to define#}
{{define SayHello}}
  Hello {{$target}}!
{{/define}}

{#to use#}
{{do SayHello target="World"}}

{#outputs "Hello World!" #}
```

I've no idea about the schema of i18n now, Lol

**Comment by 13leaf** [comment]
明白了。这个在twig里面用这种形式:

``` twig
{%macro SayHello(target)%}
    {{"Hello"~target}}
{%endmacro%}
```

其实和sass中@mixin属同样概念

**Comment by bigbigant** [comment]
了解
