### ISSUE TITLE
To support PHP short tag.

### ISSUE THREAD

**Issue by bigbigant** [Comos/tage#7]
I just added some scenarios to LexTest.
I found that Lex doesn't support PHP short tag yet.
So there's a failed assertion.

By the way, the Lex's demonstration is pretty cool!

**Comment by 13leaf** [comment]
Appreciate,I will write more fun demo later:D
Fixed short echo tag support.

And should we support PHP 4 style tags?
http://php.net/manual/zh/language.basic-syntax.phpmode.php
I think some style are so weired...

**Comment by bigbigant** [comment]
Yes. It's awful... I've almost forgotten them.
I'm hesitating in `<script>`. It helps to identify the Javascript blocks too.
The asp style tags and short tags, they will be deprecated in someday, I suppose.
So let's ignore the last two, or all of them.
